server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://192.168.0.9:5434/postgres
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
