server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://192.168.0.9:5433/postgres
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

songs-app:
  service:
    song-service:
      url: ${SONG_SERVICE_URL:http://localhost:8082/songs}
